### ISSUE TITLE
How to import coq

### ISSUE THREAD

**Issue by s1n7ax** [ms-jpq/coq_nvim#11] opened 2021-08-15 06:49 UTC
In the readme it shows following snippet.

```lua
local lsp = require "lspconfig"

lsp.<server>.setup(<stuff...>)                              -- before
lsp.<server>.setup(coq.lsp_ensure_capabilities(<stuff...>)) -- after
```

Apparently `require('coq')` is a function and what needs to be passed in to the function?

**Comment by ms-jpq** [comment] 2021-08-15 06:52
coq imports itself when your package manager loads it.

dont worry, it does like almost zero work and just registers two functions to the global scope, one to start the program when you call `:COQnow` and other one is `coq.lsp_ensure_capabilities`

**Comment by s1n7ax** [comment] 2021-08-15 08:09
```lua
    for _, lsp in ipairs(servers) do
        lspconfig[lsp].setup(coq.lsp_ensure_capabilities({
                                        ^^^ attempt to index global 'coq' (a nil value)
            on_attach = on_attach_callback,
        }))
    end
```

I'm using `packer` and loading `lspconfig`, `lspinstall` and all the other stuff after `coq`. completion starts after `:COQnow` but still get above error. One reason not to have global variable on top of other scope reasons i guess. In completion it shows the templates literally as well.
![image](https://user-images.githubusercontent.com/18459807/129471673-e3099cb2-75d9-4a26-8e5c-b5f47b0ae1ef.png)

**Comment by ms-jpq** [comment] 2021-08-15 08:24
humm im not familiar with `packer`. I will need to test it, maybe it loads plugins lazily and there is a special option not to?

`coq` does almost zero work on load so it should be ok to eagerly load it.

and yeah the snippet template showing is intentional, some snippets do not have names and only their snippet body.

Its probably best to show it imo, so you know what each one does.

**Comment by QuiiBz** [comment] 2021-08-15 08:28
Same issue here with `Plug` as a package manager: `E5108: Error executing lua [string ":lua"]:55: attempt to index global 'coq' (a nil value)`. Shouldn't we put a `require("coq")`?

**Comment by s1n7ax** [comment] 2021-08-15 08:32
Are you sure `plugin/coq.vim` is getting called when there is a `coq.lua` file? Otherwise in `coq.lua` setting a global variable inside the function.

**Comment by ms-jpq** [comment] 2021-08-15 08:41
OH `packer` skips calling `plugin/coq.nvim` if `coq.lua` exists?

I will need to investigate that, I assumed all plugin managers called `*.vim` files, always.

**Comment by ms-jpq** [comment] 2021-08-15 08:43
I will do that tomorrow probably, i have no brain cells left for tonight,

and I promise my mom id go to Ikea with her, so tomorrow night, sorry about delay

**Comment by s1n7ax** [comment] 2021-08-15 09:20
@ms-jpq Ok i checked it. `coq.vim` also being loaded.

I added some print statements

```
my conf
coq.vim
coq.lua
```

Somehow someway this is the order. It was not because packer lazy loading it (I think) because packer does not lazy load unless there are additional loading conditions are there. In my case I don't have any conditions.

**Comment by matu3ba** [comment] 2021-08-15 14:30
@ms-jpq Did you try putting every variable and function into a table and return the table?

```lua
local M = {}
M.config = default_config
function M.init(config)
...
end
return M

```
and then calling via
```vim
lua require("iswap").init()
command ...
```
should work. For some reason also `function init()`. 

I dont understand the usage of luaeval and how it interacts with luaeval. My guess is that you try to use `call` which only works for calling vim code.
Why do you need the coq.vim at all? You can just use a function for the setup, which the user calls.

**Comment by creativenull** [comment] 2021-08-15 19:24
Investigating this as well, seems like `coq` is a global variable that is set from `lua/coq.lua` so looks like if you're lazy loading it with packer BUT setting your `lspconfig` setups before loading `coq.nvim` then it will not work. You want to make sure it is loaded before your lspconfig setups, and usually it's discouraged to lazy load `lspconfig` as it does it's own lazy loading internally so it won't hurt to load them both on demand (Will need to see if it's possible to just lazy load `coq.nvim`).

Best thing is to not lazy load it and just load it on demand, then you have the `coq` variable available, no need to `require('coq')`, `plugin/coq.vim` will require it and set the `coq` global variable:

```lua
-- load with packer
use {'neovim/nvim-lspconfig'}
use {'ms-jpq/coq_nvim'}
...

-- somewhere after packer have loaded lspconfig and coq
lsp.<server>.setup(coq.lsp_ensure_capabilities(<your config>)) 

```

**Comment by ms-jpq** [comment] 2021-08-15 19:30
I think @creativenull has got this?

I will try it later after IKEA and put it in the docs.

---

@matu3ba I actually need `coq.vim` for a single reason: 

```viml
let s:top_level = resolve(expand('<sfile>:p:h:h'))
```

I need the absolute path of `coq.nvim`'s install folder so I can figure out where to store stuff. I think I can probably remove this though.

**Comment by matu3ba** [comment] 2021-08-15 20:52
> let s:top_level = resolve(expand('<sfile>:p:h:h'))

plenary.nvim (intended to be eventually nvim lua std) has a convenient [parent method](https://github.com/nvim-lua/plenary.nvim/blob/0b78fe699b9049b8f46942664027b32102979832/lua/plenary/path.lua#L553) and `:absolute`.

Unfortunately there is still no git library or anything in plenary for getting the git_root (which would be a clearner solution).
see this issue https://github.com/nvim-lua/wishlist/issues/6

plenary.nvim is already used by telescope, so using it as dependency would not be too much of an additional dependency.

nvim-lspconfig uses inside utils.lua are hacky search reverse 100 times until you find a `.git` in the folder.

**Comment by ms-jpq** [comment] 2021-08-15 21:57
oh wtf, `packer` actually loads everything! lazily by default. I will need to read the docs to find out how to mark `coq` as an exception, as it performs it's own lazy loading

**Comment by creativenull** [comment] 2021-08-15 23:58
Pretty sure when calling `:PackerCompile` will make it lazy load next time? But i'm not too sure how exactly packer does it w/o the compile file. It could be they lazy load everything like you said, but then what's the use of them adding the plugins in `pack/*/start/*` directory by default when no options are passed loading via packer.

**Comment by s1n7ax** [comment] 2021-08-16 01:28
@ms-jpq I tried to remove `expand('<sfile>:p:h:h')` calling it inside the `coq.lua`

```lua
print(api.nvim_eval("expand('<sfile>:p:h:h')"))
print(api.nvim_eval("expand('<sfile>:p:h')"))
print(api.nvim_eval("expand('<sfile>:p')"))

> /home/s1n7ax/.config/nvim
> /home/s1n7ax/.config/nvim/plugin
> /home/s1n7ax/.config/nvim/plugin/packer_compiled.lua
```

So you are going to need that `coq.vim`.

**Comment by ms-jpq** [comment] 2021-08-16 01:31
yeah thank you for the help, ive been testing this and its tricky. because `packer` tries to lazy load `coq.nvim` while `coq.nvim` is already lazily loaded, the double lazy loading thing obviously doesn't work.

**Comment by ms-jpq** [comment] 2021-08-16 02:56
Ok i  think I got it

https://github.com/ms-jpq/coq_nvim/pull/26

```lua
vim.schedule(function ()
  local lsp = require "lspconfig"
  require("packer").loader("coq_nvim coq.artifacts")
  lsp.<server>.setup(require("coq")().lsp_ensure_capabilities(<stuff...>))
end)
```

had to read packers code to figure it out

**Comment by s1n7ax** [comment] 2021-08-16 03:09
I guess you don't need to manually load if it is being accessed in the next event loop and it is a dependency. This works for me
```lua
use {
    'kabouzeid/nvim-lspinstall',
    run = function()
        require('nvim.plugins.lspinstall').install_servers()
    end,
    requires = {
        {'neovim/nvim-lspconfig'}
    },
}

use {
    'neovim/nvim-lspconfig',
    config = function() require('nvim.plugins.lsp') end,
    requires = {
        {'ms-jpq/coq_nvim', branch = 'coq'},
        {'ms-jpq/coq.artifacts', branch = 'artifacts'},
    },
}
```

```lua
vim.schedule(function()
    vim.cmd('COQnow')
    for _, lsp in ipairs(servers) do
        lspconfig[lsp].setup(coq.lsp_ensure_capabilities({
            on_attach = on_attach_callback,
        }))
    end
end)
```

**Comment by ms-jpq** [comment] 2021-08-16 03:10
thanks @s1n7ax  I will add your comment to the readme.

**Comment by ms-jpq** [comment] 2021-08-16 03:13
I dont think `COQnow` is required though, that will **eagerly load** `coq.nvim`.

unless you want that of course

**Comment by s1n7ax** [comment] 2021-08-16 03:16
O_o It won't start unless I add `COQnow`. Plugin is up to date

**Comment by ms-jpq** [comment] 2021-08-16 03:24
0.o ok maybe use my manual load method haha, I guess ill remove ur comment to reduce confusion.

oh and everybody please update your repo or else my snippet wont work.

**Comment by npielawski** [comment] 2021-08-16 06:27
I don't know if I didn't update properly or if the issue only addressed Packer, but I still get the nil value problem. I am using Plugged.

**Comment by ms-jpq** [comment] 2021-08-16 06:28
Oh ok nevermind, I thought it only affected `packer`. I will test out `Plugged` and see what it does different.

**Comment by akinsho** [comment] 2021-08-16 17:18
FWIW packer does not lazy load by default. One of the main differences between it and other solutions is that it uses vim's native packages feature `:h packages` this means that the time when things are loaded is different to other package managers that manually manipulate vim's runtimepath. One key difference is that it means that native packages load *after* a user's `init` file is read.

>  When Vim starts up, after processing your .vimrc, it scans all directories in
'packpath' for plugins under the "pack/*/start" directory.  First all those
directories are added to 'runtimepath'.  Then all the plugins are loaded.
See |packload-two-steps| for how these two steps can be useful.

In the specific case of this plugin I think the issue is that unlike other `lua` modules that conventionally expose their modules to then be used programatically, this plugin returns a function from it's lua module which *it* then tries to load in the `plugin` directory, so this is likely happening later than when a user might try to use it in their packer setup.

I think a better solution would be to just return the `coq` module from the `lua` module so a user can `require'coq'.lsp_stuff()`. If the module is dependent on the location of the script then you can alternatively use
```lua
function script_path()
   local str = debug.getinfo(2, "S").source:sub(2)
   return str:match("(.*/)")
end

print(script_path())
```
to get the location of the file that the function was called from ([source](https://stackoverflow.com/questions/6380820/get-containing-path-of-lua-file))

So the coq module should do something more like
```lua
local coq = {}
function coq.setup()
 local start_location = ... -- derive this with the above snippet
 ... -- other stuff
end

function coq.lsp_function_thing()
 -- logic here
end

return coq -- rather than return function() ... end
```

**Comment by ms-jpq** [comment] 2021-08-19 08:40
https://github.com/ms-jpq/coq_nvim/pull/88

its done.

I will close this issue. If things still don't work, please re-open it.

**Closed as completed by ms-jpq** 2021-08-19 08:40 UTC

**Comment by ilhamfu** [comment] 2021-11-21 10:34
for some reason, I got the same issue. this is the script that I placed in the after/plugin directory. I'm using vim-plug as my package manager.
```
lua << EOF
    local nvim_lsp = require 'lspconfig'
    local coq = require "coq"
    
    local on_attach = function(client, bufnr)
        local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
        local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

        buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')
  
        local opts = { noremap=true, silent=true }

        buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
        buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)

    end

    nvim_lsp.intelephense.setup(coq.lsp_ensure_capabillities({
        on_attach = on_attach,
        flags = {
            debounce_text_chages = 150,
        }
    }))

    nvim_lsp.html.setup(coq.lsp_ensure_capabillities({
        on_attach = on_attach,
        flags = {
            debounce_text_changes = 150,
        },
        file_types = {"html",'blade'}
    }))

EOF
```
