### ISSUE TITLE
Complete candidates popup is blinking too much.

### ISSUE THREAD

**Issue by AllenDang** [ms-jpq/coq_nvim#14] opened 2021-08-15 10:51 UTC
The speed is very very very fast! One side effect is the candidates popup is blinking on every key stroke.

The gif seems ok due to the compression...

![commatolines](https://user-images.githubusercontent.com/18550/129475974-925c4914-b611-47d5-a68d-070d2ba3fbf8.gif)

Any chance to avoid it?

**Comment by markdestouches** [comment] 2021-08-15 11:28
I am having the same issue. On top of that, having the statusline constantly switch between INSERT and INSERT COMPL on every keystroke (even when there are no completion suggestions) is quite annoying.

**Comment by Shougo** [comment] 2021-08-15 14:04
You can disable mode display by `set noshowmode`...

**Comment by markdestouches** [comment] 2021-08-15 21:01
> You can disable mode display by `set noshowmode`...

I am talking about plugins like airline, not the default vim statusline.

**Comment by Shougo** [comment] 2021-08-16 00:06
> I am talking about plugins like airline, not the default vim statusline.

Oh.  But you have not described it in the comment...  So I have confused.
https://github.com/ms-jpq/coq_nvim/issues/14#issuecomment-899036142

The configuration fixed for me.

```vim
let g:airline_mode_map = {
      \ 'i'      : 'INSERT',
      \ 'ic'     : 'INSERT',
      \ }
```

**Comment by ms-jpq** [comment] 2021-08-16 06:22
@AllenDang 

Not really, I dont think nvim has any API for me to update the completion menu without closing the old one.

@Shougo please correct me if im wrong, I know you are very experienced in this:

The only way to really update the completion menu (without just adding in more results) as of nvim 0.5 is to close it and open a new one, which causes the flickering.

---

I could use nvim's built-in filtering which will be better in terms of like flickering, but then `coq.nvim` will lose out being able to do fuzzy searches.

There is a [PR on this](https://github.com/neovim/neovim/pull/13854), but I dont think it will go in before 0.6.

My instinct tells me that having a more advanced error correcting fuzzy search is worth it in terms of the trade offs.

**Comment by Gelio** [comment] 2021-08-16 07:18
@ms-jpq To me, the problem is that the completions popup is mounted at the cursor's position and that changes after every keystroke. This is also visible in the gif.

I've taken a look at how https://github.com/hrsh7th/nvim-compe handles that problem and it looks like they mount the completions popup at the beginning of the word, not the cursor position:


https://user-images.githubusercontent.com/889383/129525707-8feb761b-b49c-40e6-b064-00f85fbfb368.mp4

Maybe it would be worth implementing the same solution? Then we could see if the flickering is still a problem.

**Comment by ms-jpq** [comment] 2021-08-16 07:21
interesting, that does seem to help!

thank you, i will try that

**Comment by Shougo** [comment] 2021-08-16 10:37
>@Shougo please correct me if im wrong, I know you are very experienced in this:

Hi.  I have called.

> I've taken a look at how hrsh7th/nvim-compe handles that problem and it looks like they mount the completions popup at the beginning of the word, not the cursor position:

Yes.  I think it is the reason.
`coq_nvim` create the completion window at cursor position.
It means, the cursor position changes when filtering.
So neovim must hide the completion window and redraw the window.

If the completion window at the beginning of the word, neovim does not hide the current completion window.  Because the completion window begin is not changed.

**Comment by hrsh7th** [comment] 2021-08-16 17:51
I don't think the flickering is caused by the completion menu location.
the cursor will be moved to the right so neovim can keep showing the completion menu. (But this approach will make flicker when the user press backspace.

But I'm sorry. If coq_nvim is specifying `equal=1` property for all completion items, I can't imagine the root cause.

**Comment by Shougo** [comment] 2021-08-16 21:08
>  If coq_nvim is specifying equal=1 property for all completion items, I can't imagine the root cause.

`coq_nvim` already sets `equal=1` for candidates.

**Comment by Shougo** [comment] 2021-08-16 21:10
When users use `backspace`, it will be flicker in other completion plugins.
It changes complete position.  I think the change complete position is the root cause.

**Comment by hrsh7th** [comment] 2021-08-17 05:20
The completion position is not a root cause. because the same behavior without flickering can realize as the below screencast.

https://user-images.githubusercontent.com/629908/129667930-2b98e3bf-aec5-491d-8602-6e3a985b2720.mp4

I think we should check `complete(offset, candidates)` calls.

**Comment by ms-jpq** [comment] 2021-08-17 05:57
I think I got it. please pull from latest and see if you guys are happy.

I made COQ slightly faster and disabled flickering, except for when you hit backspace,

**Comment by hrsh7th** [comment] 2021-08-17 05:58
The flickering has gone with latest commit 👍🏼

**Comment by ms-jpq** [comment] 2021-08-17 06:01
woah quick response!

man I should have added this before I recorded all the gifs, now i am too lazy to re-record them.

oh well

**Comment by mcchrish** [comment] 2021-08-17 06:36
Well at least when the demos need to be recreated you can make use of github's video attachments for higher resolution. Only downside is that it's not autoplay.

**Comment by ms-jpq** [comment] 2021-08-17 06:38
shoot, i think i introduced a bug

**Comment by ms-jpq** [comment] 2021-08-17 07:09
ima disable the anti-flicker for now, im too tired to fix the bug today, will fix tomorow

---
edit:


hummm,

this is harder than I thought, disabling the thing which causes flickering seems to significantly reduce `coq.nvim`'s speed.

I suspect that has something to do with the textlocks.

**Comment by bytesizedpcs** [comment] 2021-08-25 03:28
Is this still being worked on?

**Comment by ms-jpq** [comment] 2021-08-25 15:54
Yes,
 there is a branch for it https://github.com/ms-jpq/coq_nvim/tree/noflicker

I am using it today for work, if I dont notice any issues. I will merge it

**Comment by ms-jpq** [comment] 2021-08-25 15:56
so far it looks ok!

**Comment by ms-jpq** [comment] 2021-08-25 16:16
it's merged

---


## Flickering

By default, the old results are cleared on each keystroke, so the popup menu is closed right away.

You can disable this: at the cost of having stale results shown until the new ones come in.

`let g:coq_settings = { 'display.pum.fast_close': v:false }`

This is not the default because some LSP servers are very slow (ie. tailwindcss), leading to stale results being shown for too long.

**Closed as completed by ms-jpq** 2021-08-25 16:16 UTC

**Comment by ms-jpq** [comment] 2021-08-25 16:24
tailwindcss is particularly bad because by default, it even shows up in filetypes like markdown, leading to unreasonable lag in text files.

**Comment by rodhash** [comment] 2021-09-19 05:10
wow so many genius here! you all made our (neo)vim lifes so much better!

this latest commit improved well, to me the completion menu doesn't disapear any longer but flickers faster, is it just me? just tried a fresh install but still the same

Well since now it stays visible all the time it's looking better to me .. the "faster" flicker won't bother that much .. thanks!
