### ISSUE TITLE
Feature: Pum icons for LspKind and source

### ISSUE THREAD

**Issue by ray-x** [ms-jpq/coq_nvim#138] opened 2021-08-27 00:17 UTC
There is a placeholder in default.yml.  display.pum.icons
I am wondering how to map the LspKind and Source to nerfont icons/emoji
e.g. 
display.pum.icons = {'Function': 🅕, 'treesitter': 🌴}

**Comment by ms-jpq** [comment] 2021-08-30 04:18
duplicate of https://github.com/ms-jpq/coq_nvim/issues/87

I will start work on that soon 👍

**Closed as completed by ms-jpq** 2021-08-30 04:18 UTC

**Comment by ms-jpq** [comment] 2021-08-30 23:55
![icons.png](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/icons.png)

**Comment by ray-x** [comment] 2021-08-31 04:18
Thanks!
Is it possible to show the icon only? That will give move spaces in the popup menu.

e.g.
![image](https://user-images.githubusercontent.com/1681295/131440982-9086c795-eea8-4f87-aafd-f2b564e568fb.png)

**Comment by ms-jpq** [comment] 2021-08-31 04:20
`let g:coq_settings = { 'display.icons.mode': 'short' }`

:)
