### ISSUE TITLE
Error end_col out of bounds (with latest update)

### ISSUE THREAD

**Issue by smjonas** [ms-jpq/coq_nvim#179] opened 2021-08-31 14:27 UTC
Hey, I got this random error:

```
end_col out of bounds
Traceback (most recent call last):
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
logging.py", line 31, in with_suppress
    yield None
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
lib.py", line 43, in wrapper
    return await aw
  File "/home/jonas/.vim/plugged/coq_nvim/coq/server/registrants/omnifunc.py", line 189, in co
nt
    inserted = await async_call(
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
lib.py", line 83, in async_call
    return await loop.run_in_executor(None, fut.result)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
lib.py", line 74, in cont
    ret = fn(*args, **kwargs)
  File "/home/jonas/.vim/plugged/coq_nvim/coq/server/registrants/omnifunc.py", line 191, in <l
ambda>
    lambda: edit(
  File "/home/jonas/.vim/plugged/coq_nvim/coq/server/edit.py", line 361, in edit
    _correct(nvim, buf=buf, pos=state.context.position, before=before)
  File "/home/jonas/.vim/plugged/coq_nvim/coq/server/edit.py", line 353, in _correct
    nvim.api.buf_set_text(buf, row, l1, row, h1, (replace,))
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/api
/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/msg
pack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: end_col out of bounds

```
I believe this happened after the Neovim window gained focus again (I had Firefox open, then switched back to Neovim by left clicking). Unfortunately I cannot reproduce this. Maybe you have an idea what could be causing this :)

**Comment by ms-jpq** [comment] 2021-09-01 16:46
https://github.com/ms-jpq/coq_nvim/pull/189

I think its due to a rare race condition.

ill close it for now since I can't reproduce it, and I assume the extra check I added fixes it.

if i see it again ill reopen this

**Closed as completed by ms-jpq** 2021-09-01 16:46 UTC

**Comment by smjonas** [comment] 2021-09-05 10:43
Thanks, I did not get this error again. However I just got a similar one, this time for `start_col`:
```json
start_col out of bounds
Traceback (most recent call last):
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
logging.py", line 31, in with_suppress
    yield None
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
lib.py", line 43, in wrapper
    return await aw
  File "/home/jonas/.vim/plugged/coq_nvim/coq/server/registrants/omnifunc.py", line 224, in co
nt
    await async_call(nvim, cont)
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
lib.py", line 83, in async_call
    return await loop.run_in_executor(None, fut.result)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/
lib.py", line 74, in cont
    ret = fn(*args, **kwargs)
  File "/home/jonas/.vim/plugged/coq_nvim/coq/server/registrants/omnifunc.py", line 220, in co
nt
    inserted = edit(nvim, stack=stack, state=s, data=ud)
  File "/home/jonas/.vim/plugged/coq_nvim/coq/server/edit.py", line 417, in edit
    nvim.api.buf_set_text(buf, n_row, p_col, n_row, p_col, (inserted,))
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/api
/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/jonas/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/msg
pack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: start_col out of bounds
```
