### ISSUE TITLE
LSP Setup Not Working: `attempt to index local 'coq'`

### ISSUE THREAD

**Issue by sbernheim4** [ms-jpq/coq_nvim#17] opened 2021-08-15 15:52 UTC
Saw your reddit post last night and I'm excited to try this out. Having some trouble installing it and getting it to work. 

From the readme:
```
Install the Nvim Official LSP integration

Requires 1 line of change to support LSP snippets

local lsp = require "lspconfig"

lsp.<server>.setup(<stuff...>)                              -- before
lsp.<server>.setup(coq.lsp_ensure_capabilities(<stuff...>)) -- after
```

When I do this and then open neovim I get an error of 

```
Error detected while processing /Users/sambernheim/.config/nvim/init.vim:
line  201:
E5108: Error executing lua [string ":lua"]:53: attempt to index local 'coq' (a function value)
```

My lsp config setup currently is 

```
lspconfig.tsserver.setup{
    root_dir = lspconfig.util.root_pattern("package.json", "tsconfig.json", ".git")
}
```

Following your suggestions I make it 

```
lspconfig.tsserver.setup{
    coq.lsp_ensure_capabilities(
        root_dir = lspconfig.util.root_pattern("package.json", "tsconfig.json", ".git")
    )
}
```

and then I see the error. 
I've also tried several different variations (parentheses instead of curly braces, removing the `root_dir` line, etc)

I'm on an M1 Mac if its relevant. I've run `COQdeps` and `COQnow` as well and both succeeded.

I think at least one other person on the reddit thread is also having this issue.

**Comment by sagarc03** [comment] 2021-08-15 16:00
duplicate of #11

**Comment by sagarc03** [comment] 2021-08-15 16:02
Duplicate of #11

**Comment by sbernheim4** [comment] 2021-08-15 16:08
If I try and require it via

```
local coq = require 'coq'
```

before the `setup` call, I get the same issue

**Comment by ms-jpq** [comment] 2021-08-16 05:56
There was an issue affecting those who used `packer` package manager.

because both `packer` and `coq.nvim` did their own lazyloading, what ended up happening was that `coq.nvim` ended up not being loaded at all.

I have pushed a fix to main, please pull the latest changes.

and use: 

```lua
vim.schedule(function ()
  local lsp = require "lspconfig"
  require("packer").loader("coq_nvim coq.artifacts")
  lsp.<server>.setup(require("coq")().lsp_ensure_capabilities(<stuff...>))
end)
```

this is in the docs now

**Closed as completed by ms-jpq** 2021-08-16 05:56 UTC
