### ISSUE TITLE
Rendering markdown in preview window

### ISSUE THREAD

**Issue by MiragonMx** [ms-jpq/coq_nvim#410] opened 2021-12-15 12:26 UTC
I've not been able to find something in that regard, so I wondered what could be done to render the markdown in the docs-preview window. As you can see in the below screenshot, only the (highlighted) plain markdown is shown opposed to the gifs in the main readme, where the previews are more nice to look at.
Tested with pyright, nvim builtin lsp

![image](https://user-images.githubusercontent.com/80544476/146186430-fe3e4c50-ed1f-4cea-8439-98ed5dbcda88.png)

**Comment by dnaaun** [comment] 2022-01-03 07:50
This is a duplicate of #209 right? Might wanna close this issue if that's the case.

**Comment by ms-jpq** [comment] 2022-01-04 05:20
yeah its a dup, i will close it.


https://github.com/ms-jpq/coq_nvim/pull/428

But there is some improvements! all the `&nbsp` and friends should be unescaped into their original characters 👍

**Closed as completed by ms-jpq** 2022-01-04 05:20 UTC
