### ISSUE TITLE
Autocomplete with tab(like nvim come)

### ISSUE THREAD

**Issue by samrathchadha** [ms-jpq/coq_nvim#194] opened 2021-09-02 01:08 UTC
Instead of tab just going to the next item could it select the next and insert it? The key trigger could still be there for snippets and such.

**Comment by darthdeus** [comment] 2021-09-02 01:17
What a coincidence, I literally came here to ask the same thing, and you just asked it 8 minutes ago. It seems this thing I used to use for deoplete doesn't work in coq

```
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><s-TAB>  pumvisible() ? "\<C-p>" : "\<TAB>"
```

**Comment by samrathchadha** [comment] 2021-09-02 01:37
Thats because it just goes to the next item...

**Comment by zeertzjq** [comment] 2021-09-02 02:04
I think this is a duplicate of #90

**Comment by darthdeus** [comment] 2021-09-02 02:20
> Thats because it just goes to the next item...

It does, but the way other completion engines can be configured is that pressing `TAB` once completes the first item while keeping the completion popup open, and pressing `TAB` again moves to the second item in the already shown completion list.

This lets the user only use `TAB` to both complete the most likely option, and to select an alternative from the list, instead of using `TAB` as _goto next_ and `Enter` as _finish completion_. The suggested workflow basically saves one keystroke in every case other than completing the first option, and doesn't require the user to use two separate hotkeys.

**Comment by zeertzjq** [comment] 2021-09-02 23:22
> > Thats because it just goes to the next item...
> 
> It does, but the way other completion engines can be configured is that pressing `TAB` once completes the first item while keeping the completion popup open, and pressing `TAB` again moves to the second item in the already shown completion list.
> 
> This lets the user only use `TAB` to both complete the most likely option, and to select an alternative from the list, instead of using `TAB` as _goto next_ and `Enter` as _finish completion_. The suggested workflow basically saves one keystroke in every case other than completing the first option, and doesn't require the user to use two separate hotkeys.

Actually any printable character also finishes completion.

**Comment by samrathchadha** [comment] 2021-09-03 02:42
> Actually any printable character also finishes completion.

That's what I currently do, I want tab to act like the current tab + printable character.

**Comment by zeertzjq** [comment] 2021-09-03 03:00
Then this is a duplicate of #90.

**Closed as completed** 2021-09-03 04:46 UTC
