### ISSUE TITLE
Feature request: adding brackets automatically

### ISSUE THREAD

**Issue by quantum-booty** [ms-jpq/coq_nvim#151] opened 2021-08-28 22:51 UTC
It would be nice if it could add brackets automatically when you press tab to select a function.
![image](https://user-images.githubusercontent.com/28958399/131232883-fbf1bd2c-89f5-4360-bfb3-2e4c217f4e35.png)

**Comment by dnaaun** [comment] 2021-08-29 04:12
This is a duplicate of #91  . I believe the current plan is to implement this feature in the future, but if you want a work around, on the discussion on #91  , someone posted a guide on how to use this with a stand alone "auto pairs" plugin.

**Comment by zeertzjq** [comment] 2021-08-29 05:48
> This is a duplicate of #91 . I believe the current plan is to implement this feature in the future, but if you want a work around, on the discussion on #91 , someone posted a guide on how to use this with a stand alone "auto pairs" plugin.

No, this isn't a duplicate of #91. #91 doesn't mention anything about inserting parentheses immediately after completion.

**Comment by dnaaun** [comment] 2021-08-29 07:44
>  #91 doesn't mention anything about inserting parentheses mmediately after completion

Yes. I stand corrected. This isn't a duplicate.

**Comment by ms-jpq** [comment] 2021-08-29 20:09
sorry I will not implement this.

the reason is that this is the LSP's job, nice LSPs like `rust-analyzer` will already send snippets like `print($0)`, where `$0` locates the cursor between `(` and `)`.

without writing an LSP myself, I have no way of knowing if semantically, `print` is being invoked, or merely being passed around into a higher order function.

if its the former, turning `print` into `print($0)` certainly makes sense, but for the latter, its counter productive, and very annoying.

**Comment by ms-jpq** [comment] 2021-08-29 20:10
also for rust it's pretty easy, since `print!` is a macro, and can't be passed around as a function pointer

**Closed as completed by ms-jpq** 2021-08-29 20:09 UTC

**Comment by kaiuri** [comment] 2022-03-26 15:43
[try](https://github.com/ms-jpq/coq_nvim/issues/91#issuecomment-1079709069) this instead
